// <auto-generated />
using ChickenFarmApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChickenFarmApi.DataAccess.Migrations
{
    [DbContext(typeof(EggLayingContext))]
    [Migration("20231125211623_AddChicken.cs")]
    partial class AddChickencs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ChickenFarmApi.DataAccess.Entities.Chicken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chickens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Chicken");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChickenFarmApi.DataAccess.Entities.EggLayingRecord", b =>
                {
                    b.HasBaseType("ChickenFarmApi.DataAccess.Entities.Chicken");

                    b.Property<int>("ChickenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EggCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ChickenId");

                    b.HasDiscriminator().HasValue("EggLayingRecord");
                });

            modelBuilder.Entity("ChickenFarmApi.DataAccess.Entities.EggLayingRecord", b =>
                {
                    b.HasOne("ChickenFarmApi.DataAccess.Entities.Chicken", "Chicken")
                        .WithMany()
                        .HasForeignKey("ChickenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chicken");
                });
#pragma warning restore 612, 618
        }
    }
}
